name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
defaults:
  run:
    working-directory: ./wine-tastery
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Install dependencies
        run: |
          pnpm install
      - name: Deploy Sanity
        run: |
          set -e
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" pnpm deploy
