name: Deploy Sanity

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

defaults:
  run:
    working-directory: ./wine-tastery

jobs:
  deploy:
    runs-on: ubuntu-latest

  name: Deploy Sanity
  steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pnpm install

    - name: Deploy Sanity Studio
      run: pnpm run deploy
