name: Deploy Sanity
on:
  push:
    branches: [main]
jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    name: Deploy Sanity
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: npm install -g @sanity/cli &&
          sanity install &&
          SANITY_AUTH_TOKEN=$SANITY_AUTH_TOKEN &&
          sanity deploy
